[package]
name = "game-off-2018"
version = "0.1.0"
authors = ["Jordan West <jordwest@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.4"
nalgebra = "0.16.8"
ncollide2d = "0.17.1"
nphysics2d = "0.9.2"
